import Head from "next/head";
import styles from "@/styles/Home.module.css";
import { FormEvent, useState } from "react";

export default function Home() {
  const [seminarID, setSeminatID] = useState("");

  const submitHandler = (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault();
    console.log(seminarID);
  };
  return (
    <>
      <Head>
        <title>Obrfm Analytics</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <form className={styles.div} onSubmit={submitHandler}>
          <label>Введите номер семинара</label>
          <input
            value={seminarID}
            onChange={(e) => setSeminatID(e.target.value)}
          />
          <input type="submit" value="Отправить" />
        </form>
      </main>
    </>
  );
}
